"""Initial schema: all ORM models (users, jobs, posts, accounts, ...).

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-09-17 08:37:43.551661+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)

    op.create_table('saved_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cookies', sa.Text(), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_accounts_owner_id'), ['owner_id'], unique=False)

    op.create_table('scrape_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pages_total', sa.Integer(), nullable=False),
    sa.Column('pages_completed', sa.Integer(), nullable=False),
    sa.Column('posts_found', sa.Integer(), nullable=False),
    sa.Column('posts_processed', sa.Integer(), nullable=False),
    sa.Column('posts_skipped', sa.Integer(), nullable=False),
    sa.Column('posts_failed', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('storage_duplicates', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_jobs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_jobs_status'), ['status'], unique=False)

    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_jobs_job_id'), ['job_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('page_name', sa.String(length=512), nullable=True),
    sa.Column('page_id', sa.String(length=128), nullable=True),
    sa.Column('posts_discovered', sa.Integer(), nullable=False),
    sa.Column('posts_extracted', sa.Integer(), nullable=False),
    sa.Column('duplicates_removed', sa.Integer(), nullable=False),
    sa.Column('posts_skipped', sa.Integer(), nullable=False),
    sa.Column('posts_failed', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'normalized_url', name='uq_sources_job_url')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_status'), ['status'], unique=False)

    op.create_table('crawl_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('posts_extracted', sa.Integer(), nullable=False),
    sa.Column('posts_stored', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_states_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_states_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_states_status'), ['status'], unique=False)

    op.create_table('errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('post_url', sa.String(length=2048), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_errors_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_errors_source_id'), ['source_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=128), nullable=True),
    sa.Column('dedup_key', sa.String(length=192), nullable=False),
    sa.Column('facebook_url', sa.String(length=2048), nullable=True),
    sa.Column('post_url', sa.String(length=2048), nullable=True),
    sa.Column('page_name', sa.String(length=512), nullable=True),
    sa.Column('page_id', sa.String(length=128), nullable=True),
    sa.Column('profile_url', sa.String(length=2048), nullable=True),
    sa.Column('post_type', sa.String(length=16), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('external_links', sa.JSON(), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('media_url', sa.String(length=2048), nullable=True),
    sa.Column('video_url', sa.String(length=2048), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_language', sa.String(length=16), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'dedup_key', name='uq_posts_source_dedup_key')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_posts_job_published', ['job_id', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_source_id'), ['source_id'], unique=False)

    op.create_table('engagement_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('reaction_like_count', sa.Integer(), nullable=True),
    sa.Column('reaction_love_count', sa.Integer(), nullable=True),
    sa.Column('reaction_care_count', sa.Integer(), nullable=True),
    sa.Column('reaction_haha_count', sa.Integer(), nullable=True),
    sa.Column('reaction_wow_count', sa.Integer(), nullable=True),
    sa.Column('reaction_sad_count', sa.Integer(), nullable=True),
    sa.Column('reaction_angry_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagement_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagement_metrics_post_id'), ['post_id'], unique=True)

    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('video_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_post_id'))

    op.drop_table('media')
    with op.batch_alter_table('engagement_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagement_metrics_post_id'))

    op.drop_table('engagement_metrics')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_source_id'))
        batch_op.drop_index(batch_op.f('ix_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_posts_post_id'))
        batch_op.drop_index(batch_op.f('ix_posts_page_id'))
        batch_op.drop_index('ix_posts_job_published')
        batch_op.drop_index(batch_op.f('ix_posts_job_id'))

    op.drop_table('posts')
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_errors_source_id'))
        batch_op.drop_index(batch_op.f('ix_errors_job_id'))

    op.drop_table('errors')
    with op.batch_alter_table('crawl_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_states_status'))
        batch_op.drop_index(batch_op.f('ix_crawl_states_source_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_states_job_id'))

    op.drop_table('crawl_states')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_status'))
        batch_op.drop_index(batch_op.f('ix_sources_job_id'))

    op.drop_table('sources')
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_jobs_job_id'))

    op.drop_table('export_jobs')
    with op.batch_alter_table('scrape_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_scrape_jobs_owner_id'))

    op.drop_table('scrape_jobs')
    with op.batch_alter_table('saved_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_accounts_owner_id'))

    op.drop_table('saved_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))

    op.drop_table('users')
    # ### end Alembic commands ###
